# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'car_karaoke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for car_karaoke

  pod 'AudioKit', '~> 4.0'

  target 'car_karaokeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'car_karaokeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
