# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDL_player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDL_player
	
  pod 'SmartDeviceLink', '~> 6.1'
  
  target 'SDL_playerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDL_playerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
